spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_blog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
application:
  secret: notsecret